#!/bin/bash
VERSION="$1"

if [[ ! "$VERSION" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "Please pass in a valid, alphanumeric version number/ID to push to." >&2
  exit
fi

gulp

cat app/app.yaml | sed "s/___VERSION_NUMBER___/$VERSION/g" > dist/app.yaml


appcfg.py update --no_cookies dist
